# Generated by Django 5.2.7 on 2025-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(default='Explore', max_length=100)),
                ('button_link', models.CharField(default='/shop', max_length=200)),
                ('image_url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GiftOfferSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('button_text', models.CharField(default='Explore Gift Offers', max_length=100)),
                ('button_link', models.CharField(default='/shop', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('cta_text', models.CharField(default='Shop Now', max_length=100)),
                ('cta_link', models.CharField(default='/shop', max_length=200)),
                ('image_url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('button_text', models.CharField(default='Browse Essentials', max_length=100)),
                ('button_link', models.CharField(default='/shop', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_key', models.CharField(choices=[('money_back', 'Money Back'), ('shipping', 'Fast Shipping'), ('support', '24/7 Support'), ('custom', 'Custom')], default='custom', help_text='Frontend isme se icon choose karega', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('link_text', models.CharField(max_length=100)),
                ('link_url', models.CharField(default='/', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaticHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('button_link', models.CharField(default='/shop', max_length=200)),
                ('image_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Static Hero Banner',
                'verbose_name_plural': 'Static Hero Banners',
            },
        ),
    ]
