# Generated by Django 5.2.7 on 2025-11-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredoffer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statichero',
            options={},
        ),
        migrations.AddField(
            model_name='featuredoffer',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image (priority over URL)', null=True, upload_to='homepage/featured_offer/'),
        ),
        migrations.AddField(
            model_name='giftoffersection',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image (priority over URL)', null=True, upload_to='homepage/gift_offer/'),
        ),
        migrations.AddField(
            model_name='giftoffersection',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: Enter image URL (Used only if no image uploaded)', null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image (priority over URL)', null=True, upload_to='homepage/hero_slides/'),
        ),
        migrations.AddField(
            model_name='statichero',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image (If both are provided, uploaded image is used)', null=True, upload_to='homepage/static/'),
        ),
        migrations.AlterField(
            model_name='featuredoffer',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: Enter image URL (Used only if no image uploaded)', null=True),
        ),
        migrations.AlterField(
            model_name='giftoffersection',
            name='button_text',
            field=models.CharField(default='Explore Gifts', max_length=100),
        ),
        migrations.AlterField(
            model_name='giftoffersection',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: Enter image URL (Used only if no image uploaded)', null=True),
        ),
        migrations.AlterField(
            model_name='statichero',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: Enter an image URL (Only used if no image is uploaded)', null=True),
        ),
    ]
