# Generated by Django 5.2.7 on 2025-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_featuredoffer_options_alter_heroslide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryhero',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload hero banner image', null=True, upload_to='homepage/secondary_hero/'),
        ),
        migrations.AddField(
            model_name='secondaryhero',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: External image URL (used if upload missing)', null=True),
        ),
    ]
