# Generated by Django 5.2.7 on 2025-11-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_secondaryhero_image_secondaryhero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeature',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload service feature image', null=True, upload_to='homepage/service_features/'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: Image URL (used only if upload missing)', null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='icon_key',
            field=models.CharField(choices=[('money_back', 'Money Back'), ('shipping', 'Fast Shipping'), ('support', '24/7 Support'), ('custom', 'Custom')], default='custom', help_text='Auto icon (Frontend will show icon based on this)', max_length=20),
        ),
    ]
