# Generated by Django 5.2.7 on 2025-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_servicefeature_image_servicefeature_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeature',
            name='cms_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='link_type',
            field=models.CharField(choices=[('cms', 'CMS Page'), ('system', 'System Page'), ('shop', 'Shop Page'), ('external', 'External URL')], default='external', max_length=20),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='shop_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='system_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='featuredoffer',
            name='button_link',
            field=models.CharField(default='/shop', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='giftoffersection',
            name='button_link',
            field=models.CharField(default='/shop', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_link',
            field=models.CharField(default='/shop', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='secondaryhero',
            name='button_link',
            field=models.CharField(default='/shop', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='icon_key',
            field=models.CharField(choices=[('money_back', 'Money Back'), ('shipping', 'Fast Shipping'), ('support', '24/7 Support'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/service_features/'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='link_text',
            field=models.CharField(default='Learn More', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='link_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='statichero',
            name='button_link',
            field=models.CharField(default='/shop', editable=False, max_length=200),
        ),
    ]
