# Generated by Django 5.2.7 on 2025-11-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_servicefeature_cms_page_servicefeature_link_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicefeature',
            name='cms_page',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='shop_page',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='system_page',
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='link_page',
            field=models.CharField(blank=True, choices=[('CMS:about', 'CMS → About Us'), ('CMS:contact', 'CMS → Contact Us'), ('CMS:privacy', 'CMS → Privacy Policy'), ('CMS:terms', 'CMS → Terms of Use'), ('CMS:shipping', 'CMS → Shipping Policy'), ('CMS:returns', 'CMS → Return & Refund'), ('SYS:track-order', 'System → Track Order'), ('SYS:orders-returns', 'System → Orders & Returns'), ('SYS:sitemap', 'System → Site Map'), ('SYS:cart', 'System → Cart'), ('SYS:wishlist', 'System → Wishlist'), ('SYS:my-orders', 'System → My Orders'), ('SHOP:shop', 'Shop → Shop Page'), ('SHOP:all-products', 'Shop → All Products')], help_text='Select the page that should open when button is clicked.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='link_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='link_type',
            field=models.CharField(choices=[('cms', 'CMS Page'), ('system', 'System Page'), ('shop', 'Shop Page'), ('external', 'External URL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='link_url',
            field=models.CharField(blank=True, help_text='Used only when Link Type = External URL', max_length=300),
        ),
    ]
