# Generated by Django 5.2.7 on 2025-12-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_bottomnavcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomnavcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
