# Generated by Django 5.2.7 on 2025-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
