# Generated by Django 5.2.7 on 2025-11-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('intro_text', models.TextField(blank=True)),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_description', models.TextField(blank=True)),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_description', models.TextField(blank=True)),
                ('stat_1_label', models.CharField(default='Happy Customers', max_length=200)),
                ('stat_1_value', models.CharField(default='10K+', max_length=100)),
                ('stat_2_label', models.CharField(default='Cities Served', max_length=200)),
                ('stat_2_value', models.CharField(default='12+', max_length=100)),
                ('stat_3_label', models.CharField(default='Products Delivered', max_length=200)),
                ('stat_3_value', models.CharField(default='500+', max_length=100)),
                ('stat_4_label', models.CharField(default='Customer Rating', max_length=200)),
                ('stat_4_value', models.CharField(default='4.9★', max_length=100)),
                ('who_we_are', models.TextField(blank=True)),
                ('why_choose_us', models.TextField(blank=True, help_text='Add each point in new line.')),
                ('cta_text', models.CharField(default='Explore Our Store', max_length=200)),
                ('cta_link', models.CharField(default='/shop', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
