# Generated by Django 5.2.7 on 2025-11-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_footeraboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=200)),
                ('intro_text', models.TextField(blank=True, default='Have questions or need support? Our team is here to help you.')),
                ('phone_number', models.CharField(default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(default='support@myecommerce.com', max_length=254)),
                ('address', models.CharField(default='123 Market Road, Delhi, India', max_length=300)),
                ('working_hours', models.CharField(default='Mon - Sat: 9:00 AM - 7:00 PM', max_length=200)),
                ('map_embed_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12...')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
