# Generated by Django 5.2.7 on 2025-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRefundPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Return & Refund Policy', max_length=200)),
                ('intro_text', models.TextField(blank=True, default='We want you to have a smooth and worry-free shopping experience. If you are not fully satisfied, you may be eligible for a return or refund.')),
                ('section1_title', models.CharField(default='1. Return Eligibility', max_length=200)),
                ('section1_content', models.TextField(blank=True)),
                ('section2_title', models.CharField(default='2. Refund Process', max_length=200)),
                ('section2_content', models.TextField(blank=True)),
                ('section3_title', models.CharField(default='3. Replacement Policy', max_length=200)),
                ('section3_content', models.TextField(blank=True)),
                ('section4_title', models.CharField(default='4. Non-Returnable Items', max_length=200)),
                ('section4_content', models.TextField(blank=True)),
                ('section5_title', models.CharField(default='5. Cancellation Policy', max_length=200)),
                ('section5_content', models.TextField(blank=True)),
                ('section6_title', models.CharField(default='6. How to Request a Return', max_length=200)),
                ('section6_content', models.TextField(blank=True)),
                ('footer_note', models.TextField(blank=True, default='We are committed to ensuring you have a smooth experience with us.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
