# Generated by Django 5.2.7 on 2025-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0005_returnrefundpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('intro_text', models.TextField(blank=True)),
                ('section1_title', models.CharField(default='1. Information We Collect', max_length=200)),
                ('section1_content', models.TextField(blank=True)),
                ('section2_title', models.CharField(default='2. How We Use Your Information', max_length=200)),
                ('section2_content', models.TextField(blank=True)),
                ('section3_title', models.CharField(default='3. Data Protection', max_length=200)),
                ('section3_content', models.TextField(blank=True)),
                ('section4_title', models.CharField(default='4. Third-Party Services', max_length=200)),
                ('section4_content', models.TextField(blank=True)),
                ('section5_title', models.CharField(default='5. Contact Us', max_length=200)),
                ('section5_content', models.TextField(blank=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
