# Generated by Django 5.2.7 on 2025-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0006_privacypolicypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUsePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms of Use', max_length=200)),
                ('intro_text', models.TextField(blank=True, default='By using this website, you agree to the terms and conditions mentioned on this page. Please read them carefully.')),
                ('section1_title', models.CharField(default='1. Use of Our Website', max_length=200)),
                ('section1_content', models.TextField(blank=True, default='You agree to use this website only for lawful purposes and in a way that does not harm our brand, services, or other users.')),
                ('section2_title', models.CharField(default='2. Account & Security', max_length=200)),
                ('section2_content', models.TextField(blank=True, default='You are responsible for maintaining the confidentiality of your account details and for all activities that happen under your account.')),
                ('section3_title', models.CharField(default='3. Orders & Payments', max_length=200)),
                ('section3_content', models.TextField(blank=True, default='All orders placed on our website are subject to availability and final confirmation. Payments are processed securely through trusted partners.')),
                ('section4_title', models.CharField(default='4. Content & Ownership', max_length=200)),
                ('section4_content', models.TextField(blank=True, default='All content, logos, images, and product information on this site are owned or licensed by us and cannot be copied or used without permission.')),
                ('section5_title', models.CharField(default='5. Changes to These Terms', max_length=200)),
                ('section5_content', models.TextField(blank=True, default='We may update these Terms of Use from time to time. Continued use of the website after changes means you accept the updated terms.')),
                ('footer_note', models.CharField(blank=True, default='Last updated: 01 Jan 2025', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
