# Generated by Django 5.2.7 on 2025-11-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0007_termsofusepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Shipping Policy', max_length=200)),
                ('intro_text', models.TextField(blank=True, default='This page explains how your orders are packed, shipped, and delivered. Please read carefully before placing an order.')),
                ('section1_title', models.CharField(default='1. Order Processing Time', max_length=200)),
                ('section1_content', models.TextField(blank=True, default='Most orders are processed and dispatched within 1–2 business days. During high demand, processing may take slightly longer.')),
                ('section2_title', models.CharField(default='2. Delivery Time', max_length=200)),
                ('section2_content', models.TextField(blank=True, default='Delivery usually takes 3–7 business days depending on your location and courier availability.')),
                ('section3_title', models.CharField(default='3. Shipping Charges', max_length=200)),
                ('section3_content', models.TextField(blank=True, default='Shipping charges, if applicable, will be shown during checkout before you complete your order.')),
                ('section4_title', models.CharField(default='4. Order Tracking', max_length=200)),
                ('section4_content', models.TextField(blank=True, default='Once your order is shipped, you will receive a tracking link or AWB number on your email/SMS to track your shipment.')),
                ('section5_title', models.CharField(default='5. Delayed or Lost Orders', max_length=200)),
                ('section5_content', models.TextField(blank=True, default='In rare cases of delay or lost shipments, please contact our support team. We will coordinate with the courier partner and resolve the issue.')),
                ('footer_note', models.CharField(blank=True, default='Last updated: 01 Jan 2025', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
