# Generated by Django 5.2.7 on 2025-11-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0008_shippingpolicypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='page_type',
            field=models.CharField(blank=True, choices=[('about', 'About Us'), ('contact', 'Contact Us'), ('shipping', 'Shipping Policy'), ('returns', 'Return / Refund Policy'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], help_text='Select a CMS page to auto-generate URL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, help_text='Used only for system/external links. CMS pages auto-generate URL.', max_length=300),
        ),
    ]
