# Generated by Django 5.2.7 on 2025-11-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0009_footerlink_page_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='page_type',
            field=models.CharField(blank=True, choices=[('about', 'About Us'), ('contact', 'Contact Us'), ('shipping', 'Shipping Policy'), ('returns', 'Return / Refund Policy'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], help_text='Select only for CMS pages', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, help_text='For system/external links. CMS pages auto-generate URL.', max_length=300),
        ),
    ]
