# Generated by Django 5.2.7 on 2025-11-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0010_alter_footerlink_page_type_alter_footerlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='page_type',
            field=models.CharField(blank=True, choices=[('about', 'About Us'), ('contact', 'Contact Us'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('shipping', 'Shipping Policy'), ('returns', 'Return & Refund Policy'), ('track-order', 'Track Order Page'), ('orders-returns', 'Orders & Return Page'), ('sitemap', 'Site Map Page')], help_text='Select desired page. URL will be auto-generated.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, help_text='Will be overwritten automatically based on page type.', max_length=300),
        ),
    ]
