# Generated by Django 5.2.7 on 2025-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0011_alter_footerlink_page_type_alter_footerlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeraboutpage',
            name='cta_link',
            field=models.CharField(default='/shop', editable=False, max_length=200),
        ),
    ]
