# Generated by Django 5.2.7 on 2025-12-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0012_alter_footeraboutpage_cta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeraboutpage',
            name='cta_text',
            field=models.CharField(blank=True, default='Explore Our Store', max_length=200),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='intro_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='mission_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=200),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='stat_1_label',
            field=models.CharField(blank=True, default='Happy Customers', max_length=200),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='stat_1_value',
            field=models.CharField(blank=True, default='10K+', max_length=100),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='stat_2_label',
            field=models.CharField(blank=True, default='Cities Served', max_length=200),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='stat_2_value',
            field=models.CharField(blank=True, default='12+', max_length=100),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='stat_3_label',
            field=models.CharField(blank=True, default='Products Delivered', max_length=200),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='stat_3_value',
            field=models.CharField(blank=True, default='500+', max_length=100),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='stat_4_label',
            field=models.CharField(blank=True, default='Customer Rating', max_length=200),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='stat_4_value',
            field=models.CharField(blank=True, default='4.9★', max_length=100),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='title',
            field=models.CharField(blank=True, default='About Us', max_length=200),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='vision_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='vision_title',
            field=models.CharField(blank=True, default='Our Vision', max_length=200),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='who_we_are',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='why_choose_us',
            field=models.TextField(blank=True, default='', help_text='Add each point in new line.'),
        ),
    ]
