# Generated by Django 5.2.7 on 2025-12-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0013_alter_footeraboutpage_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeraboutpage',
            name='intro_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='mission_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='vision_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='who_we_are',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footeraboutpage',
            name='why_choose_us',
            field=models.TextField(blank=True),
        ),
    ]
