# Generated by Django 5.2.7 on 2025-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0014_alter_footeraboutpage_intro_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='footer_note',
            field=models.CharField(blank=True, default='Last updated: 01 Jan 2025', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='intro_text',
            field=models.TextField(blank=True, default='This page explains how your orders are packed, shipped, and delivered. Please read carefully before placing an order.', null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section1_content',
            field=models.TextField(blank=True, default='Most orders are processed...', null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section1_title',
            field=models.CharField(blank=True, default='1. Order Processing Time', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section2_content',
            field=models.TextField(blank=True, default='Delivery usually takes 3–7 days...', null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section2_title',
            field=models.CharField(blank=True, default='2. Delivery Time', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section3_content',
            field=models.TextField(blank=True, default='Shipping charges...', null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section3_title',
            field=models.CharField(blank=True, default='3. Shipping Charges', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section4_content',
            field=models.TextField(blank=True, default='Once shipped you will receive tracking...', null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section4_title',
            field=models.CharField(blank=True, default='4. Order Tracking', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section5_content',
            field=models.TextField(blank=True, default='In rare cases of delay...', null=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicypage',
            name='section5_title',
            field=models.CharField(blank=True, default='5. Delayed or Lost Orders', max_length=200, null=True),
        ),
    ]
