# Generated by Django 5.2.7 on 2025-12-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0015_alter_shippingpolicypage_footer_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofusepage',
            name='footer_note',
            field=models.CharField(blank=True, default='Last updated: 01 Jan 2025', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section1_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section1_title',
            field=models.CharField(blank=True, default='1. Acceptance of Terms', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section2_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section2_title',
            field=models.CharField(blank=True, default='2. Use of Our Services', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section3_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section3_title',
            field=models.CharField(blank=True, default='3. User Responsibilities', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section4_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section4_title',
            field=models.CharField(blank=True, default='4. Limitations of Liability', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section5_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsofusepage',
            name='section5_title',
            field=models.CharField(blank=True, default='5. Governing Law', max_length=200, null=True),
        ),
    ]
