# Generated by Django 5.2.7 on 2025-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0016_alter_termsofusepage_footer_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturnPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Order & Return', max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('footer_note', models.CharField(blank=True, default='Last updated: 01 Jan 2025', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='returnrefundpage',
            name='section6_content',
        ),
        migrations.RemoveField(
            model_name='returnrefundpage',
            name='section6_title',
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='footer_note',
            field=models.CharField(blank=True, default='Last updated: 01 Jan 2025', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section1_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section1_title',
            field=models.CharField(blank=True, default='1. Return Eligibility', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section2_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section2_title',
            field=models.CharField(blank=True, default='2. Refund Process', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section3_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section3_title',
            field=models.CharField(blank=True, default='3. Non-Returnable Items', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section4_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section4_title',
            field=models.CharField(blank=True, default='4. Cancellation Policy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section5_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrefundpage',
            name='section5_title',
            field=models.CharField(blank=True, default='5. Contact Support', max_length=200, null=True),
        ),
    ]
