# Generated by Django 5.2.7 on 2025-12-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0017_orderreturnpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderReturnPage',
        ),
    ]
