# Generated by Django 5.2.7 on 2025-11-28 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_average_rating_product_total_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Admin seed rating (1-5 stars)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Admin assumed number of initial reviewers'),
        ),
    ]
