# Generated by Django 5.2.7 on 2025-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, help_text='Optional — If provided, this image will be used.', null=True, upload_to='category/icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, help_text='Optional — If provided, this image will be used.', null=True, upload_to='category/'),
        ),
    ]
