# Generated by Django 5.2.7 on 2025-11-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_category_icon_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image_url',
            field=models.URLField(blank=True, help_text='Optional image URL for category (used if no uploaded image)', null=True),
        ),
    ]
